import { test, expect } from '@playwright/test'

test('cold static subpath visit: isolation, real solve, tour and repairs', async ({ page }) => {
  const errors: string[] = []
  const requests: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (request.url().startsWith('http')) requests.push(request.url()) })
  await page.goto('./')
  await expect(page.getByRole('heading', { name: 'Can this neighbourhood deliver?' })).toBeVisible()
  await expect(page).toHaveTitle('A plan that fits · Explore constraint solving on a real map')
  await expect(page.getByRole('status')).toContainText('Z3 ready', { timeout: 60000 })
  expect(await page.evaluate(() => crossOriginIsolated && typeof SharedArrayBuffer !== 'undefined')).toBe(true)
  expect(await page.evaluate(async () => (await navigator.serviceWorker.getRegistration())?.scope)).toBe('http://127.0.0.1:5187/tour/')
  const direct = await page.request.get('./')
  expect(direct.headers()['cross-origin-opener-policy']).toBeUndefined()
  await expect(page.getByRole('region', { name: 'What is a constraint solver?' })).toContainText('A constraint is a rule that must be met')
  await expect(page.getByRole('link', { name: 'An introduction to constraint solving' })).toHaveAttribute('href', 'https://developers.google.com/optimization/cp')
  await expect(page.locator('.interaction-note')).toContainText('Step 1 is for inspection')
  await page.getByText('Where did the candidate sites come from?', { exact: true }).click()
  await expect(page.locator('.candidate-explanation')).toContainText('15 locker candidates A–O are invented for this lesson')
  await expect(page.locator('.candidate-explanation')).toContainText('80 m apart')
  await expect(page.locator('.candidate-explanation')).toContainText('two possible collection sites')
  await page.getByText('Where did the candidate sites come from?', { exact: true }).click()
  const openLockers = await page.locator('.map-locker.active').evaluateAll(elements => elements.map(element => element.textContent))
  await page.getByLabel('Inspect a collection journey').selectOption({ index: 1 })
  expect(await page.locator('.map-locker.active').evaluateAll(elements => elements.map(element => element.textContent))).toEqual(openLockers)
  await expect(page.getByRole('button', { name: 'Map depot West', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Map locker B: candidate, not open', exact: true })).toBeDisabled()
  await page.screenshot({ path: test.info().outputPath('01-start.png'), fullPage: true })
  await page.getByRole('button', { name: 'Try the plan', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Build a plan that fits.' })).toBeVisible()
  await expect(page.locator('.locker-picker button[aria-pressed="true"]')).toHaveCount(0)
  await expect(page.locator('.game-checks .pass')).toHaveCount(0)
  await expect(page.locator('.game-checks')).toContainText('Choose lockers to check supply reach')
  await page.screenshot({ path: test.info().outputPath('01-game-empty.png'), fullPage: true })
  await expect(page.locator('.game-scale')).toContainText('38,610')
  await expect(page.getByTestId('map-game-help')).toContainText('Click locker circles and depot labels to toggle them')
  await expect(page.getByRole('button', { name: /^Map locker A: not selected/ })).toBeEnabled()
  await page.getByRole('button', { name: /^Map locker A: not selected/ }).click()
  await expect(page.getByRole('button', { name: /^Map locker A: selected/ })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: /^Map locker B: not selected/ }).click()
  await expect(page.getByRole('button', { name: /^Map locker B: selected/ })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Clear my plan' }).click()
  await expect(page.locator('.locker-picker button[aria-pressed="true"]')).toHaveCount(0)
  await page.getByRole('button', { name: /^Map locker A: not selected/ }).click()
  for (const id of ['C', 'D', 'E', 'G', 'K', 'L', 'N']) await page.getByRole('button', { name: `Locker ${id}`, exact: true }).click()
  await page.getByRole('button', { name: 'Map depot West', exact: true }).click()
  await expect(page.getByRole('button', { name: '◇ West', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: /Map locker H: not selected; outside all selected depots' 2 km return range/ })).toHaveAttribute('data-supply-reach', 'out-of-range')
  await expect(page.getByRole('button', { name: /Map locker H: not selected; outside all selected depots' 2 km return range/ })).toHaveClass(/out-of-depot-range/)
  await expect(page.getByRole('button', { name: /Map locker I: not selected; within range of a selected depot/ })).toHaveAttribute('data-supply-reach', 'within-range')
  await expect(page.getByTestId('map-game-help')).toContainText('Coral rings mark lockers outside every selected depot')
  await expect(page.getByRole('group', { name: 'Map legend' })).toContainText('Outside selected depot range')
  await page.screenshot({ path: test.info().outputPath('01-game-range.png'), fullPage: true })
  await page.getByRole('button', { name: 'Map depot South', exact: true }).click()
  await page.getByRole('button', { name: 'Check my plan with Z3', exact: true }).click()
  const result = page.getByTestId('solver-result')
  await expect(result).toHaveAttribute('data-status', 'unsat')
  await expect(result).toContainText('This exact site selection does not work')
  // Editing invalidates the old claim immediately, without a new solve.
  await page.getByRole('button', { name: 'Map depot South', exact: true }).click()
  await expect(result).toHaveCount(0)
  await page.getByRole('button', { name: 'Map depot East', exact: true }).click()
  await expect(page.locator('.game-checks')).toContainText('Every cell has a selected locker within 500 m')
  await expect(page.locator('.game-checks')).toContainText('Every selected locker has a chosen depot in range')
  await page.getByRole('button', { name: 'Check my plan with Z3', exact: true }).click()
  await expect(result).toHaveAttribute('data-status', 'feasible')
  await expect(result).toContainText('You found a plan that fits')
  await page.screenshot({ path: test.info().outputPath('01-game-win.png'), fullPage: true })
  await page.getByRole('button', { name: 'Let Z3 find a plan' }).click()
  await expect(result).toHaveAttribute('data-status', 'feasible')
  await expect(result).toContainText('Z3 found a connected network')
  await expect(page.locator('.locker-picker button[aria-pressed="true"]')).toHaveCount(8)
  await page.getByRole('button', { name: 'Reveal the conflict', exact: true }).click()
  await page.getByRole('button', { name: 'Ask Z3 to check every choice' }).click()
  await expect(result).toHaveAttribute('data-status', 'unsat')
  await expect(result).toContainText('keeping exactly the starter lockers')
  await page.screenshot({ path: test.info().outputPath('02-conflict.png'), fullPage: true })
  await page.getByRole('button', { name: 'Let Z3 choose the whole network' }).click()
  await page.getByRole('button', { name: 'Find a connected network' }).click()
  await expect(result).toHaveAttribute('data-status', 'feasible')
  await expect(result).toContainText('all 871 parcels assigned')
  await expect(result).toContainText('separate JavaScript verified 33 walks')
  await expect(page.locator('.flight-detail')).toContainText('return flight')
  await page.getByLabel('Inspect a collection journey').selectOption({ index: 15 })
  await page.screenshot({ path: test.info().outputPath('03-solved.png'), fullPage: true })
  await page.getByRole('button', { name: 'Compare both search methods' }).click()
  const comparison = page.getByTestId('solver-comparison')
  await expect(comparison).toContainText('Both methods reached the same feasible conclusion', { timeout: 60000 })
  await expect(comparison.getByRole('row', { name: /Z3 Plan found/ })).toBeVisible()
  await expect(comparison.getByRole('row', { name: /Brute-force JS Plan found/ })).toBeVisible()
  await expect(comparison).toContainText('collection-assignment branches')
  await page.screenshot({ path: test.info().outputPath('04-comparison-feasible.png'), fullPage: true })
  await page.getByLabel('Question to compare').selectOption('impossible')
  await page.getByRole('button', { name: 'Compare both search methods' }).click()
  await expect(comparison).toContainText('Both methods reached the same UNSAT conclusion', { timeout: 60000 })
  await expect(comparison.getByRole('row', { name: /Z3 Proved impossible/ })).toBeVisible()
  await expect(comparison.getByRole('row', { name: /Brute-force JS Proved impossible/ })).toBeVisible()
  await expect(comparison).toContainText('16,384 locker sets')
  await page.screenshot({ path: test.info().outputPath('05-comparison-impossible.png'), fullPage: true })
  await page.getByRole('button', { name: 'Explore the trade-offs' }).click()
  for (const name of ['Keep the lockers. Add a depot.', 'Keep the lockers. Extend drone range.']) {
    await page.getByRole('button', { name, exact: false }).click()
    await expect(result).toHaveAttribute('data-status', 'feasible')
  }
  await page.getByRole('button', { name: 'Can we manage with seven lockers?', exact: false }).click()
  await expect(result).toHaveAttribute('data-status', 'unsat')
  await expect(result).toContainText('No combination of the 15 candidate lockers')
  await expect(page.locator('body')).not.toHaveCSS('overflow-x', 'scroll')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(requests.filter(url => !url.startsWith('http://127.0.0.1:5187/tour/'))).toEqual([])
  expect(errors).toEqual([])
})

test('keyboard-accessible explanation and explicit unsupported-browser state', async ({ page }) => {
  await page.addInitScript(() => Object.defineProperty(window, 'crossOriginIsolated', { get: () => false }))
  await page.goto('./')
  await expect(page.getByRole('heading', { name: 'Can this neighbourhood deliver?' })).toBeVisible()
  await expect(page.getByRole('status')).toContainText('The browser needs site isolation')
  const method = page.getByRole('button', { name: 'How it works' })
  await method.focus(); await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('dialog')).toContainText('not a claim that Z3 is the only tool')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(method).toBeFocused()
})
