"""Typed contracts for building reproducible, location-driven scenarios.

This package is deliberately independent from the current Four Planters runtime.
It defines the input and provenance seam for future builders without changing the
checked-in Kallio--Vallila scenario or solver API.
"""

from .adapters import (
    AdapterConfigurationError,
    AdapterRegistry,
    SourceAcquisitionContext,
    SourceAdapter,
    source_adapter_workspace,
)
from .espoo import (
    ESPOO_ADAPTER_ID,
    ESPOO_LAYERS,
    ESPOO_SOURCE_CRS,
    ESPOO_WFS_ENDPOINT,
    EspooArchiveError,
    EspooWfsAdapter,
    load_espoo_archive,
)
from .espoo import derive_wfs_url as derive_espoo_wfs_url
from .models import (
    ANALYSIS_CRS,
    DEFAULT_NETWORK_CONTEXT_BUFFER_M,
    MAX_NETWORK_CONTEXT_BUFFER_M,
    RECIPE_SCHEMA_VERSION,
    SNAPSHOT_SCHEMA_VERSION,
    ArtifactDigest,
    CoverageAssessment,
    FieldLineage,
    GeoJsonPolygon,
    LicenceRecord,
    LonLat,
    PointRadiusArea,
    PolygonArea,
    ScenarioRecipe,
    ScenarioSnapshotMetadata,
    SourceDeclaration,
    SourceSnapshotMetadata,
)
from .roadworks import (
    ROADWORKS_CRS,
    ROADWORKS_SCHEMA_VERSION,
    FixedSchedule,
    FlexibleSchedule,
    LineStringGeometry,
    MultiLineStringGeometry,
    PolygonGeometry,
    RoadworkFeature,
    RoadworkProperties,
    RoadworksFeatureCollection,
    RoadworksSource,
    RoadworksValidationError,
    load_roadworks_geojson,
    parse_roadworks_geojson,
)
from .syke import (
    SEA_FLOOD_1_IN_100,
    SEA_FLOOD_1_IN_1000,
    SYKE_ADAPTER_ID,
    SYKE_SEA_FLOOD_LAYERS,
    SYKE_WFS_ENDPOINT,
    SykeArchiveError,
    SykeCoastalFloodAdapter,
    derive_wfs_url,
    load_syke_archive,
)

__all__ = [
    "ANALYSIS_CRS",
    "DEFAULT_NETWORK_CONTEXT_BUFFER_M",
    "ESPOO_ADAPTER_ID",
    "ESPOO_LAYERS",
    "ESPOO_SOURCE_CRS",
    "ESPOO_WFS_ENDPOINT",
    "MAX_NETWORK_CONTEXT_BUFFER_M",
    "RECIPE_SCHEMA_VERSION",
    "ROADWORKS_CRS",
    "ROADWORKS_SCHEMA_VERSION",
    "SEA_FLOOD_1_IN_100",
    "SEA_FLOOD_1_IN_1000",
    "SNAPSHOT_SCHEMA_VERSION",
    "SYKE_ADAPTER_ID",
    "SYKE_SEA_FLOOD_LAYERS",
    "SYKE_WFS_ENDPOINT",
    "AdapterConfigurationError",
    "AdapterRegistry",
    "ArtifactDigest",
    "CoverageAssessment",
    "EspooArchiveError",
    "EspooWfsAdapter",
    "FieldLineage",
    "FixedSchedule",
    "FlexibleSchedule",
    "GeoJsonPolygon",
    "LicenceRecord",
    "LineStringGeometry",
    "LonLat",
    "PointRadiusArea",
    "PolygonArea",
    "PolygonGeometry",
    "MultiLineStringGeometry",
    "RoadworkFeature",
    "RoadworkProperties",
    "RoadworksFeatureCollection",
    "RoadworksSource",
    "RoadworksValidationError",
    "ScenarioRecipe",
    "ScenarioSnapshotMetadata",
    "SourceAcquisitionContext",
    "SourceAdapter",
    "SourceDeclaration",
    "SourceSnapshotMetadata",
    "SykeArchiveError",
    "SykeCoastalFloodAdapter",
    "derive_espoo_wfs_url",
    "derive_wfs_url",
    "load_espoo_archive",
    "load_roadworks_geojson",
    "load_syke_archive",
    "parse_roadworks_geojson",
    "source_adapter_workspace",
]
